### ISSUE TITLE
Require recycle warnings

### ISSUE THREAD

**Issue by WSINTRA** [WSINTRA/Savour_v1#17]
Currently when I open the app in expo on my phone I get a Require recycle warning for some of that tab navigation components. Any ideas on what this means?
Do you get the same warnings?

**Comment by bcsaxon** [comment]
hmmm I've never seen that warning before.. I'm headed to a meeting ATM. but could take a peek late tonight or tomorrow for sure. excited to scope this new repo out!

**Comment by bcsaxon** [comment]
are we forking then cloning or just pulling from master and branching?

**Comment by speckworks** [comment]
Just pull and git checkout -b myNewBranch

**Comment by WSINTRA** [comment]
Figured this one out...
To prevent from having to write multiple lines of 
```
import SomeComponent from "../components"
import AnotherComponent from "../components"
import AndAnotherComponent from "../components"
import AndOneMoreComponent from "../components"
```

I created a comp.js file where I could import the components as they are created and export them as modules.
All components are then able to be reached from one place.
So you can then have something like this in some place...
```
import { SomeComponent, AnotherComponent, AndAnotherComponent, AndOneMoreComponent} from './comp'
```
Now what happens in the renderer for example when SomeComponent is rendered....
```
import * as React from "react";
import { AnotherComponent} from '../comps';
import { View, Text } from "react-native";

function SomeComponent() {
return (
    <>
    <AnotherComponent />
    <View><Text>EXAMPLE OF SOMECOMPONENT</Text></View>
    </>
)
}
export default YourCrates;
```

In the example, SomeComponent could be called in the main App, and when it renders it also asks for a component from the comp.js 
This is what triggers the Require cycle warning because a module that was imported from one place, is then rendering and asking to import another module from the same place it was rendered from. 

What are your thoughts on this, should we revert back to using single import statements or do you think there is a danger in using the module export as it is currently setup?

The Require recycle is just a warning so it can be dismissed.

**Comment by speckworks** [comment]
👍  Weird, I've never seen that error. Keep at it.

Use Destructuring assignment whenever possible.  Import {this, theOther,
yet another} from /comps.js
Always looks cleaner.

I've got an assignment from my interview today.  50% done.  😁✊
