### ISSUE TITLE
create nav Drawer

### ISSUE THREAD

**Issue by speckworks** [WSINTRA/Savour_v1#4]
create a basic Nav Drawer component with a gear icon to open it up.

**Comment by WSINTRA** [comment]
https://reactnavigation.org/docs/drawer-based-navigation

**Comment by speckworks** [comment]
Awesome!  Thanks!  I'll use it.
J

**Comment by WSINTRA** [comment]
Created MainTitles.js that contains a Side drawer, still need to configure it to make sure it works with the bottom tab that will be created next.
